<a href="https://colab.research.google.com/github/jmichaelh/Coursera_IBM_Capstone/blob/master/Copy_of_paris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Install and Import Libraries

In [3]:
#!pip install --upgrade pip
!pip install geopandas
!pip install geopy
!pip install geocoder
!pip install geoplot
#!pip install folium
#!sudo pip3 install bs4
#!sudo pip3 install --upgrade html5lib
#!sudo pip3 install --upgrade --force-reinstall bs4
#!sudo pip3 install --upgrade beautifulsoup4

Requirement already satisfied: geopandas in /usr/local/lib/python3.6/dist-packages (0.7.0+52.g8339c1c)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.8.13.post1)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.7.0)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (2.6.1.post1)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.0.3)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.12.0)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (0.5.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (7.1.2)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (19.3.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (1.18.4)
Requirement already satisfied: geopy in /usr/local/lib/python3.6/dist-packages (1.17.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.6/dist-packages (from geopy) (1.50)
Requirement already satisfied: geocoder in /usr/local/lib/python3.6/dist-packages (1.38.1)
Requirement already satisfied: ratelim in /usr/local/lib/python3.6/dist-packages (from geocoder) (0.1.6)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from geocoder) (0.16.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from geocoder) (1.12.0)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from geocoder) (7.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from geocoder) (2.23.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ratelim->geocoder) (4.4.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (2020.4.5.1)
Collecting geoplot
  Using cached https://files.pythonhosted.org/packages/a0/40/40c264002dfba4736f35c3524f6a0e7a03458fb4fcc436ce501f541359b7/geoplot-0.4.0-py3-none-any.whl
Requirement already satisfied: descartes in /usr/local/lib/python3.6/dist-packages (from geoplot) (1.1.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from geoplot) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from geoplot) (3.2.1)
Requirement already satisfied: geopandas in /usr/local/lib/python3.6/dist-packages (from geoplot) (0.7.0+52.g8339c1c)
Collecting cartopy
  Using cached https://files.pythonhosted.org/packages/46/c1/04e50c9986842f00f7db0e7a65caa896840050d7328f74e5b7437aa01179/Cartopy-0.18.0.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

In [5]:
import numpy as np 
import pandas as pd 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import json 
from bs4 import BeautifulSoup
import bs4 as bs
import urllib.request
import pandas as pd 
from geopy.geocoders import Nominatim 
import geocoder
import requests 
import lxml.html as lh
from bs4 import BeautifulSoup
from pandas.io.json import json_normalize 
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium
import geopandas as gpd

print('Finished importing libraries.')

Finished importing libraries.

#### Pull and Parse data from website into Beautiful Soup, create a list of nieghborhoods in Atlanta GA

In [0]:
import requests
from bs4 import BeautifulSoup
import bs4 as bs
import urllib.request
import pandas as pd 

data = requests.get('http://www.parisnet.com/parismap.html')
src = data.content
soup = BeautifulSoup(src, 'html.parser')
addy = soup.find_all('h3')

In [2]:

column_names = ['Number','Arr', 'Latitude', 'Longitude']
arr = pd.DataFrame(columns = column_names)
arr['Arr'] = addy
list = []
calc = 0
while int(calc) < 26:
    list.append(calc)
    calc = int(calc) + 1
print(list)
arr['Number'] = list
arr
def get_laatlng(arr):
    lat_lng_coords = None

    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Paris ,FR'.format(arr))
        lat_lng_cooords = g.latlng 
    return lat_lng_coords

NameError: ignored

In [0]:
coords = [ get_latlng(addy) for addy in addy ]

In [11]:
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df_coords

     Latitude  Longitude
0   48.857170   2.341400
1   48.861970   2.339370
2   48.868560   2.341614
3   48.857170   2.341400
4   48.857227   2.352404
5   48.847750   2.351800
6   48.849450   2.355081
7   48.858600   2.293980
8   48.869850   2.307210
9   48.882013   2.337608
10  48.847190   2.366580
11  48.847690   2.367466
12  48.845029   2.406192
13  48.832083   2.356319
14  48.844873   2.327844
15  48.834100   2.290010
16  48.862534   2.282255
17  48.878320   2.283730
18  48.871921   2.340723
19  48.873149   2.375512
20  48.863727   2.397408
21   6.312650 -75.581160
22  48.857170   2.341400
23  48.857170   2.341400
24  48.857170   2.341400
25  48.857170   2.341400

In [12]:
arr['Latitude'] = df_coords['Latitude']
arr['Longitude'] = df_coords['Longitude']
arronds = arr.drop(22).drop(21).drop(0).drop(23).drop(24).drop(25)

list = []
calc = 0

while int(calc) < 21:
    list.append(calc)
    calc = int(calc) + 1

print(list)

arronds = pd.DataFrame(arr, columns=['Number', 'Arr', 'Latitude', 'Longitude'])


arronds = arr.drop(22).drop(21).drop(0).drop(23).drop(24).drop(25)
arronds['Arr'] = arr['Arr']
arronds['Latitude'] = arr['Latitude']
arronds['Longitude'] = arr['Longitude']
arronds['Number'] = arr['Number']
arronds = arronds.set_index('Number')

arronds.reset_index(drop=False, inplace=True)
arronds

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    Number                                  Arr   Latitude  Longitude
0        1        [1er - Louvre, Palais Royale]  48.861970   2.339370
1        2                      [2ème - Bourse]  48.868560   2.341614
2        3      [3ème - Marais, Picasso Museum]  48.857170   2.341400
3        4      [4ème - Marais, Hôtel de Ville]  48.857227   2.352404
4        5               [5ème - Latin Quarter]  48.847750   2.351800
5        6               [6ème - Saint Germain]  48.849450   2.355081
6        7                [7ème - Eiffel Tower]  48.858600   2.293980
7        8              [8ème - Champs-Elysées]  48.869850   2.307210
8        9              [9ème - Opéra, Pigalle]  48.882013   2.337608
9       10           [10ème - Canal St. Martin]  48.847190   2.366580
10      11                   [11ème - Bastille]  48.847690   2.367466
11      12                      [12ème - Bercy]  48.845029   2.406192
12      13             [13ème - Place d'Italie]  48.832083   2.356319
13      14               [14ème - Montparnasse]  48.844873   2.327844
14      15       [15ème - Parc des Expositions]  48.834100   2.290010
15      16                  [16ème - Trocadéro]  48.862534   2.282255
16      17          [17ème - Palais de Congrès]  48.878320   2.283730
17      18                 [18ème - Montmartre]  48.871921   2.340723
18      19        [19ème - Parc de la Villette]  48.873149   2.375512
19      20  [20ème - Belleville, Père Lachaise]  48.863727   2.397408

In [13]:
dfs = pd.read_html('https://en.wikipedia.org/wiki/Arrondissements_of_Paris')
for df in dfs:
    print(df)

                              Arrondissement of Paris  \
0                                             Country
1                                              Region
2                                          Department
3                                             Cantons
4                                            Communes
5                                          Préfecture
6                                               Area¹
7                                             • Total
8                                   Population (2009)
9                                             • Total
10                                          • Density
11  ¹ French Land Registry data, which exclude lak...

                            Arrondissement of Paris.1
0                                              France
1                                       Île-de-France
2                                               Paris
3                                                  20
4                                                   1
5                                               Paris
6                                               Area¹
7                                  105 km2 (41 sq mi)
8                                   Population (2009)
9                                             2234105
10                          21,000/km2 (55,000/sq mi)
11  ¹ French Land Registry data, which exclude lak...
                          0
0  Arrondissements of Paris
   Arrondissement (R for Right Bank, L for Left Bank)                 Name  \
0                                         1st (Ier) R               Louvre
1                                         2nd (IIe) R               Bourse
2                                        3rd (IIIe) R               Temple
3                                         4th (IVe) R       Hôtel-de-Ville
4                                          5th (Ve) L             Panthéon
5                                         6th (VIe) L           Luxembourg
6                                        7th (VIIe) L       Palais-Bourbon
7                                       8th (VIIIe) R               Élysée
8                                         9th (IXe) R                Opéra
9                                         10th (Xe) R             Entrepôt
10                                       11th (XIe) R           Popincourt
11                                      12th (XIIe) R              Reuilly
12                                     13th (XIIIe) L             Gobelins
13                                      14th (XIVe) L         Observatoire
14                                       15th (XVe) L            Vaugirard
15                                      16th (XVIe) R                Passy
16                                     17th (XVIIe) R  Batignolles-Monceau
17                                    18th (XVIIIe) R     Butte-Montmartre
18                                      19th (XIXe) R      Buttes-Chaumont
19                                       20th (XXe) R         Ménilmontant

                                           Area (km2)  \
0                             1.826 km2 (0.705 sq mi)
1                             0.992 km2 (0.383 sq mi)
2                             1.171 km2 (0.452 sq mi)
3                             1.601 km2 (0.618 sq mi)
4                             2.541 km2 (0.981 sq mi)
5                             2.154 km2 (0.832 sq mi)
6                             4.088 km2 (1.578 sq mi)
7                             3.881 km2 (1.498 sq mi)
8                             2.179 km2 (0.841 sq mi)
9                             2.892 km2 (1.117 sq mi)
10                            3.666 km2 (1.415 sq mi)
11  16.324 km2 (6.303 sq mi)¹6.377 km2 (2.462 sq mi)²
12                            7.146 km2 (2.759 sq mi)
13                            5.621 km2 (2.170 sq mi)
14                            8.502 km2 (3.283 sq mi)
15  16.305 km2 (6.295 sq mi)³7.846 km2 (3.029 sq mi)4
16                            5.669 km2 (2.189 sq mi)
17                            6.005 km2 (2.319 sq mi)
18                            6.786 km2 (2.620 sq mi)
19                            5.984 km2 (2.310 sq mi)

    Population(March 1999 census)  Population(July 2005 estimate)  \
0                           16888                           17700
1                           19585                           20700
2                           34248                           35100
3                           30675                           28600
4                           58849                           60600
5                           44919                           45200
6                           56985                           55400
7                           39314                           38700
8                           55838                           58500
9                           89612                           88800
10                         149102                          152500
11                         136591                          138300
12                         171533                          181300
13                         132844                          134700
14                         225362                          232400
15                         161773                          149500
16                         160860                          160300
17                         184586                          188700
18                         172730                          187200
19                         182952                          191800

   Density (2005)(inhabitants per km2) Peak of population  \
0                                 9693        before 1861
1                                20867        before 1861
2                                29974        before 1861
3                                17864        before 1861
4                                23849               1911
5                                20984               1911
6                                13552               1926
7                                 9972               1891
8                                26847               1901
9                                30705               1881
10                               41598               1911
11                       8,472¹21,687²               1962
12                               25371              20055
13                               23964               1954
14                               27335               1962
15                       9,169³19,0544               1962
16                               28277               1954
17                               31424               1931
18                               27586              20055
19                               32052               1936

                           Mayor
0     Jean-François Legaret (LR)
1        Jacques Boutault (EELV)
2          Pierre Aidenbaum (PS)
3                Ariel Weil (PS)
4         Florence Berthout (LR)
5         Jean-Pierre Lecoq (LR)
6              Rachida Dati (LR)
7       Jeanne d'Hauteserre (LR)
8           Delphine Bürkli (LR)
9       Alexandra Cordebard (PS)
10         François Vauglin (PS)
11  Catherine Baratti-Elbaz (PS)
12            Jérôme Coumet (PS)
13             Carine Petit (PS)
14          Philippe Goujon (LR)
15           Danièle Giazzi (LR)
16         Geoffroy Boulard (LR)
17           Éric Lejoindre (PS)
18         François Dagnaud (PS)
19      Frédérique Calandra (PS)
    Unnamed: 0  Arrondissement   Arrondissement's Mayor  \
0          NaN               1    Jean-François Legaret
1          NaN               2         Jacques Boutault
2          NaN               3         Pierre Aidenbaum
3          NaN               4               Ariel Weil
4          NaN               5        Florence Berthout
5          NaN               6        Jean-Pierre Lecoq
6          NaN               7             Rachida Dati
7          NaN               8      Jeanne d'Hauteserre
8          NaN               9          Delphine Bürkli
9          NaN              10              Rémi Féraud
10         NaN              11         François Vauglin
11         NaN              12  Catherine Baratti-Elbaz
12         NaN              13            Jérôme Coumet
13         NaN              14             Carine Petit
14         NaN              15          Philippe Goujon
15         NaN              16           Danièle Giazzi
16         NaN              17          Brigitte Kuster
17         NaN              18           Eric Lejoindre
18         NaN              19         François Dagnaud
19         NaN              20      Frédérique Calandra

    Arrondissement's Mayor.1 Political party  \
0                        NaN             UMP
1                        NaN            EELV
2                        NaN              PS
3                        NaN              PS
4                        NaN             UMP
5                        NaN             UMP
6                        NaN             UMP
7                        NaN             UMP
8                        NaN             UMP
9                        NaN              PS
10                       NaN              PS
11                       NaN              PS
12                       NaN              PS
13                       NaN              PS
14                       NaN             UMP
15                       NaN              LR
16                       NaN             UMP
17                       NaN              PS
18                       NaN              PS
19                       NaN              PS

                                              Notes
0                                               NaN
1                                               NaN
2                                               NaN
3   Succeeded to Christophe Girard in November 2017
4                                               NaN
5                                               NaN
6                                   European Deputy
7                                               NaN
8                                               NaN
9                                               NaN
10                                  Deputy of Paris
11                                              NaN
12                                              NaN
13                                              NaN
14                                  Deputy of Paris
15                                  Deputy of Paris
16       Member of Île-de-France's Regional Council
17                                              NaN
18                                              NaN
19                                              NaN
         vte Arrondissements of France by department  \
0  01 Ain 02 Aisne 03 Allier 04 Alpes-de-Haute-Pr...

       vte Arrondissements of France by department.1
0  01 Ain 02 Aisne 03 Allier 04 Alpes-de-Haute-Pr...
                                    vteCity of Paris  \
0  Arrondissements 1st 2nd 3rd 4th 5th 6th 7th 8t...
1  Airports Charles de Gaulle Orly Architecture B...
2  Grand Paris Paris metropolitan area Île-de-Fra...

                                  vteCity of Paris.1  \
0  Arrondissements 1st 2nd 3rd 4th 5th 6th 7th 8t...
1  Airports Charles de Gaulle Orly Architecture B...
2  Grand Paris Paris metropolitan area Île-de-Fra...

                                  vteCity of Paris.2
0  Arrondissements 1st 2nd 3rd 4th 5th 6th 7th 8t...
1                                                NaN
2  Grand Paris Paris metropolitan area Île-de-Fra...

In [14]:
paris = pd.DataFrame(dfs[2])
paris.reset_index(drop=True, inplace=False)

#paris = paris_df.drop(columns = ['index','level_0', 'key'])
paris

,"Arrondissement (R for Right Bank, L for Left Bank)",Name,Area (km2),Population(March 1999 census),Population(July 2005 estimate),Density (2005)(inhabitants per km2),Peak of population,Mayor
0,1st (Ier) R,Louvre,1.826 km2 (0.705 sq mi),16888,17700,9693,before 1861,Jean-François Legaret (LR)
1,2nd (IIe) R,Bourse,0.992 km2 (0.383 sq mi),19585,20700,20867,before 1861,Jacques Boutault (EELV)
2,3rd (IIIe) R,Temple,1.171 km2 (0.452 sq mi),34248,35100,29974,before 1861,Pierre Aidenbaum (PS)
3,4th (IVe) R,Hôtel-de-Ville,1.601 km2 (0.618 sq mi),30675,28600,17864,before 1861,Ariel Weil (PS)
4,5th (Ve) L,Panthéon,2.541 km2 (0.981 sq mi),58849,60600,23849,1911,Florence Berthout (LR)
5,6th (VIe) L,Luxembourg,2.154 km2 (0.832 sq mi),44919,45200,20984,1911,Jean-Pierre Lecoq (LR)
6,7th (VIIe) L,Palais-Bourbon,4.088 km2 (1.578 sq mi),56985,55400,13552,1926,Rachida Dati (LR)
7,8th (VIIIe) R,Élysée,3.881 km2 (1.498 sq mi),39314,38700,9972,1891,Jeanne d'Hauteserre (LR)
8,9th (IXe) R,Opéra,2.179 km2 (0.841 sq mi),55838,58500,26847,1901,Delphine Bürkli (LR)
9,10th (Xe) R,Entrepôt,2.892 km2 (1.117 sq mi),89612,88800,30705,1881,Alexandra Cordebard (PS)
10,11th (XIe) R,Popincourt,3.666 km2 (1.415 sq mi),149102,152500,41598,1911,François Vauglin (PS)
11,12th (XIIe) R,Reuilly,16.324 km2 (6.303 sq mi)¹6.377 km2 (2.462 sq mi)²,136591,138300,"8,472¹21,687²",1962,Catherine Baratti-Elbaz (PS)
12,13th (XIIIe) L,Gobelins,7.146 km2 (2.759 sq mi),171533,181300,25371,20055,Jérôme Coumet (PS)
13,14th (XIVe) L,Observatoire,5.621 km2 (2.170 sq mi),132844,134700,23964,1954,Carine Petit (PS)
14,15th (XVe) L,Vaugirard,8.502 km2 (3.283 sq mi),225362,232400,27335,1962,Philippe Goujon (LR)
15,16th (XVIe) R,Passy,16.305 km2 (6.295 sq mi)³7.846 km2 (3.029 sq mi)4,161773,149500,"9,169³19,0544",1962,Danièle Giazzi (LR)
16,17th (XVIIe) R,Batignolles-Monceau,5.669 km2 (2.189 sq mi),160860,160300,28277,1954,Geoffroy Boulard (LR)
17,18th (XVIIIe) R,Butte-Montmartre,6.005 km2 (2.319 sq mi),184586,188700,31424,1931,Éric Lejoindre (PS)
18,19th (XIXe) R,Buttes-Chaumont,6.786 km2 (2.620 sq mi),172730,187200,27586,20055,François Dagnaud (PS)
19,20th (XXe) R,Ménilmontant,5.984 km2 (2.310 sq mi),182952,191800,32052,1936,Frédérique Calandra (PS)

In [15]:
column_names = ['Arrondissement', 'Name', 'Area', 'Pop 1999', 'Pop 2005', 'Density', 'Pop Peak', 'Mayor']
paris.columns = column_names

paris_df = pd.DataFrame(paris, columns = column_names)             
paris_df

,Arrondissement,Name,Area,Pop 1999,Pop 2005,Density,Pop Peak,Mayor
0,1st (Ier) R,Louvre,1.826 km2 (0.705 sq mi),16888,17700,9693,before 1861,Jean-François Legaret (LR)
1,2nd (IIe) R,Bourse,0.992 km2 (0.383 sq mi),19585,20700,20867,before 1861,Jacques Boutault (EELV)
2,3rd (IIIe) R,Temple,1.171 km2 (0.452 sq mi),34248,35100,29974,before 1861,Pierre Aidenbaum (PS)
3,4th (IVe) R,Hôtel-de-Ville,1.601 km2 (0.618 sq mi),30675,28600,17864,before 1861,Ariel Weil (PS)
4,5th (Ve) L,Panthéon,2.541 km2 (0.981 sq mi),58849,60600,23849,1911,Florence Berthout (LR)
5,6th (VIe) L,Luxembourg,2.154 km2 (0.832 sq mi),44919,45200,20984,1911,Jean-Pierre Lecoq (LR)
6,7th (VIIe) L,Palais-Bourbon,4.088 km2 (1.578 sq mi),56985,55400,13552,1926,Rachida Dati (LR)
7,8th (VIIIe) R,Élysée,3.881 km2 (1.498 sq mi),39314,38700,9972,1891,Jeanne d'Hauteserre (LR)
8,9th (IXe) R,Opéra,2.179 km2 (0.841 sq mi),55838,58500,26847,1901,Delphine Bürkli (LR)
9,10th (Xe) R,Entrepôt,2.892 km2 (1.117 sq mi),89612,88800,30705,1881,Alexandra Cordebard (PS)
10,11th (XIe) R,Popincourt,3.666 km2 (1.415 sq mi),149102,152500,41598,1911,François Vauglin (PS)
11,12th (XIIe) R,Reuilly,16.324 km2 (6.303 sq mi)¹6.377 km2 (2.462 sq mi)²,136591,138300,"8,472¹21,687²",1962,Catherine Baratti-Elbaz (PS)
12,13th (XIIIe) L,Gobelins,7.146 km2 (2.759 sq mi),171533,181300,25371,20055,Jérôme Coumet (PS)
13,14th (XIVe) L,Observatoire,5.621 km2 (2.170 sq mi),132844,134700,23964,1954,Carine Petit (PS)
14,15th (XVe) L,Vaugirard,8.502 km2 (3.283 sq mi),225362,232400,27335,1962,Philippe Goujon (LR)
15,16th (XVIe) R,Passy,16.305 km2 (6.295 sq mi)³7.846 km2 (3.029 sq mi)4,161773,149500,"9,169³19,0544",1962,Danièle Giazzi (LR)
16,17th (XVIIe) R,Batignolles-Monceau,5.669 km2 (2.189 sq mi),160860,160300,28277,1954,Geoffroy Boulard (LR)
17,18th (XVIIIe) R,Butte-Montmartre,6.005 km2 (2.319 sq mi),184586,188700,31424,1931,Éric Lejoindre (PS)
18,19th (XIXe) R,Buttes-Chaumont,6.786 km2 (2.620 sq mi),172730,187200,27586,20055,François Dagnaud (PS)
19,20th (XXe) R,Ménilmontant,5.984 km2 (2.310 sq mi),182952,191800,32052,1936,Frédérique Calandra (PS)

#### Use geocoder to add longitude and latitude to the Atlanta Neighborhood DataFrame

In [16]:
paris_df.head()

,Arrondissement,Name,Area,Pop 1999,Pop 2005,Density,Pop Peak,Mayor
0,1st (Ier) R,Louvre,1.826 km2 (0.705 sq mi),16888,17700,9693,before 1861,Jean-François Legaret (LR)
1,2nd (IIe) R,Bourse,0.992 km2 (0.383 sq mi),19585,20700,20867,before 1861,Jacques Boutault (EELV)
2,3rd (IIIe) R,Temple,1.171 km2 (0.452 sq mi),34248,35100,29974,before 1861,Pierre Aidenbaum (PS)
3,4th (IVe) R,Hôtel-de-Ville,1.601 km2 (0.618 sq mi),30675,28600,17864,before 1861,Ariel Weil (PS)
4,5th (Ve) L,Panthéon,2.541 km2 (0.981 sq mi),58849,60600,23849,1911,Florence Berthout (LR)

### *Merge and form into single DataFrame containing location information for Arrondissements in Paris.*

In [17]:
parcoord = paris_df.merge(arronds, 'outer', right_index=True, left_index=False, right_on=None, left_on=paris_df.index)
parcoord.reset_index(drop=True, inplace=False)
parcoord.columns = ['Arr#', 'Arrond', 'Name', 	'Area',	'Pop1999',	'Pop2005', 'Density', 'PopPeak', 'Mayor', 'Number', 'Address', 	'Latitude', 'Longitude']
parcoord['Arr#'] = parcoord['Number']
parcoord.drop(columns = ['Number'])
parcoord.set_index(['Arr#'], drop=True, append=False, inplace=False, verify_integrity=True)
parcoord

,Arr#,Arrond,Name,Area,Pop1999,Pop2005,Density,PopPeak,Mayor,Number,Address,Latitude,Longitude
0,1,1st (Ier) R,Louvre,1.826 km2 (0.705 sq mi),16888,17700,9693,before 1861,Jean-François Legaret (LR),1,"[1er - Louvre, Palais Royale]",48.861970,2.339370
1,2,2nd (IIe) R,Bourse,0.992 km2 (0.383 sq mi),19585,20700,20867,before 1861,Jacques Boutault (EELV),2,[2ème - Bourse],48.868560,2.341614
2,3,3rd (IIIe) R,Temple,1.171 km2 (0.452 sq mi),34248,35100,29974,before 1861,Pierre Aidenbaum (PS),3,"[3ème - Marais, Picasso Museum]",48.857170,2.341400
3,4,4th (IVe) R,Hôtel-de-Ville,1.601 km2 (0.618 sq mi),30675,28600,17864,before 1861,Ariel Weil (PS),4,"[4ème - Marais, Hôtel de Ville]",48.857227,2.352404
4,5,5th (Ve) L,Panthéon,2.541 km2 (0.981 sq mi),58849,60600,23849,1911,Florence Berthout (LR),5,[5ème - Latin Quarter],48.847750,2.351800
5,6,6th (VIe) L,Luxembourg,2.154 km2 (0.832 sq mi),44919,45200,20984,1911,Jean-Pierre Lecoq (LR),6,[6ème - Saint Germain],48.849450,2.355081
6,7,7th (VIIe) L,Palais-Bourbon,4.088 km2 (1.578 sq mi),56985,55400,13552,1926,Rachida Dati (LR),7,[7ème - Eiffel Tower],48.858600,2.293980
7,8,8th (VIIIe) R,Élysée,3.881 km2 (1.498 sq mi),39314,38700,9972,1891,Jeanne d'Hauteserre (LR),8,[8ème - Champs-Elysées],48.869850,2.307210
8,9,9th (IXe) R,Opéra,2.179 km2 (0.841 sq mi),55838,58500,26847,1901,Delphine Bürkli (LR),9,"[9ème - Opéra, Pigalle]",48.882013,2.337608
9,10,10th (Xe) R,Entrepôt,2.892 km2 (1.117 sq mi),89612,88800,30705,1881,Alexandra Cordebard (PS),10,[10ème - Canal St. Martin],48.847190,2.366580
10,11,11th (XIe) R,Popincourt,3.666 km2 (1.415 sq mi),149102,152500,41598,1911,François Vauglin (PS),11,[11ème - Bastille],48.847690,2.367466
11,12,12th (XIIe) R,Reuilly,16.324 km2 (6.303 sq mi)¹6.377 km2 (2.462 sq mi)²,136591,138300,"8,472¹21,687²",1962,Catherine Baratti-Elbaz (PS),12,[12ème - Bercy],48.845029,2.406192
12,13,13th (XIIIe) L,Gobelins,7.146 km2 (2.759 sq mi),171533,181300,25371,20055,Jérôme Coumet (PS),13,[13ème - Place d'Italie],48.832083,2.356319
13,14,14th (XIVe) L,Observatoire,5.621 km2 (2.170 sq mi),132844,134700,23964,1954,Carine Petit (PS),14,[14ème - Montparnasse],48.844873,2.327844
14,15,15th (XVe) L,Vaugirard,8.502 km2 (3.283 sq mi),225362,232400,27335,1962,Philippe Goujon (LR),15,[15ème - Parc des Expositions],48.834100,2.290010
15,16,16th (XVIe) R,Passy,16.305 km2 (6.295 sq mi)³7.846 km2 (3.029 sq mi)4,161773,149500,"9,169³19,0544",1962,Danièle Giazzi (LR),16,[16ème - Trocadéro],48.862534,2.282255
16,17,17th (XVIIe) R,Batignolles-Monceau,5.669 km2 (2.189 sq mi),160860,160300,28277,1954,Geoffroy Boulard (LR),17,[17ème - Palais de Congrès],48.878320,2.283730
17,18,18th (XVIIIe) R,Butte-Montmartre,6.005 km2 (2.319 sq mi),184586,188700,31424,1931,Éric Lejoindre (PS),18,[18ème - Montmartre],48.871921,2.340723
18,19,19th (XIXe) R,Buttes-Chaumont,6.786 km2 (2.620 sq mi),172730,187200,27586,20055,François Dagnaud (PS),19,[19ème - Parc de la Villette],48.873149,2.375512
19,20,20th (XXe) R,Ménilmontant,5.984 km2 (2.310 sq mi),182952,191800,32052,1936,Frédérique Calandra (PS),20,"[20ème - Belleville, Père Lachaise]",48.863727,2.397408


#### Create and push data into a new csv file

In [18]:
parcoord_df = parcoord[['Number', 'Arrond', 'Name', 'Address', 'Latitude', 'Longitude']].set_index('Number')
parcoord_df

,Arrond,Name,Address,Latitude,Longitude
Number,,,,,
1,1st (Ier) R,Louvre,"[1er - Louvre, Palais Royale]",48.861970,2.339370
2,2nd (IIe) R,Bourse,[2ème - Bourse],48.868560,2.341614
3,3rd (IIIe) R,Temple,"[3ème - Marais, Picasso Museum]",48.857170,2.341400
4,4th (IVe) R,Hôtel-de-Ville,"[4ème - Marais, Hôtel de Ville]",48.857227,2.352404
5,5th (Ve) L,Panthéon,[5ème - Latin Quarter],48.847750,2.351800
6,6th (VIe) L,Luxembourg,[6ème - Saint Germain],48.849450,2.355081
7,7th (VIIe) L,Palais-Bourbon,[7ème - Eiffel Tower],48.858600,2.293980
8,8th (VIIIe) R,Élysée,[8ème - Champs-Elysées],48.869850,2.307210
9,9th (IXe) R,Opéra,"[9ème - Opéra, Pigalle]",48.882013,2.337608
10,10th (Xe) R,Entrepôt,[10ème - Canal St. Martin],48.847190,2.366580
11,11th (XIe) R,Popincourt,[11ème - Bastille],48.847690,2.367466
12,12th (XIIe) R,Reuilly,[12ème - Bercy],48.845029,2.406192
13,13th (XIIIe) L,Gobelins,[13ème - Place d'Italie],48.832083,2.356319
14,14th (XIVe) L,Observatoire,[14ème - Montparnasse],48.844873,2.327844
15,15th (XVe) L,Vaugirard,[15ème - Parc des Expositions],48.834100,2.290010
16,16th (XVIe) R,Passy,[16ème - Trocadéro],48.862534,2.282255
17,17th (XVIIe) R,Batignolles-Monceau,[17ème - Palais de Congrès],48.878320,2.283730
18,18th (XVIIIe) R,Butte-Montmartre,[18ème - Montmartre],48.871921,2.340723
19,19th (XIXe) R,Buttes-Chaumont,[19ème - Parc de la Villette],48.873149,2.375512
20,20th (XXe) R,Ménilmontant,"[20ème - Belleville, Père Lachaise]",48.863727,2.397408

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
parcoord.to_csv('paris.csv')

In [21]:
locator = Nominatim(user_agent='myGeocoder')
location = locator.geocode('Champ de Mars, Paris, France')

print('Latitude = {}, Longitude = {}'.format(location.latitude, location.longitude))

Latitude = 48.85614465, Longitude = 2.297820393322227

In [0]:
geolocator = Nominatim(user_agent='my-application')
latitude = parcoord.Latitude
longitude = parcoord.Longitude
address = {}
def dict(Number, Address):
    for Number, Address in parcoord_df:
        address['Number'] = parcoord_df.Address
        address = dict(parcoord_df[['Address']], parcoord_df[['Number']])
           
location = geolocator.geocode(address)
map = parcoord_df

In [23]:
!pip install palettable       
!pip install colorbrewer
!pip install colormap
!pip install easydev

import easydev.tools
import pandas as pd
import json
import sys
#import folium.ColorMap
sys.path.append('..')
import folium
print (folium.__file__)
print (folium.__version__)
import palettable
import palettable.colorbrewer.sequential
import colorbrewer
from palettable.colorbrewer.sequential import YlGnBu_3

Requirement already satisfied: palettable in /usr/local/lib/python3.6/dist-packages (3.3.0)
Requirement already satisfied: colorbrewer in /usr/local/lib/python3.6/dist-packages (0.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from colorbrewer) (1.12.0)
Requirement already satisfied: colormap in /usr/local/lib/python3.6/dist-packages (1.0.3)
Requirement already satisfied: easydev in /usr/local/lib/python3.6/dist-packages (0.9.38)
Requirement already satisfied: colorlog in /usr/local/lib/python3.6/dist-packages (from easydev) (4.1.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.6/dist-packages (from easydev) (4.8.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.6/dist-packages (from easydev) (0.4.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect->easydev) (0.6.0)
/usr/local/lib/python3.6/dist-packages/folium/__init__.py
0.8.3

In [24]:
import geopandas 
file_path = '/content/drive/My Drive/Colab Notebooks/arrondissements.geojson'
geo_data =  geopandas.read_file(file_path)
geo_data

,n_sq_co,n_sq_ar,objectid,l_ar,longueur,surface,perimetre,l_aroff,c_arinsee,c_ar,geometry
0,750001537,750000001,1,1er Ardt,6054.680862,1.824613e+06,6054.936862,Louvre,75101,1,"POLYGON ((2.32801 48.86992, 2.32997 48.86851, ..."
1,750001537,750000002,2,2ème Ardt,4553.938764,9.911537e+05,4554.104360,Bourse,75102,2,"POLYGON ((2.35152 48.86443, 2.35095 48.86341, ..."
2,750001537,750000017,17,17ème Ardt,10775.348915,5.668835e+06,10775.579516,Batignolles-Monceau,75117,17,"POLYGON ((2.29517 48.87396, 2.29504 48.87378, ..."
3,750001537,750000014,14,14ème Ardt,10316.720258,5.614877e+06,10317.483310,Observatoire,75114,14,"POLYGON ((2.33381 48.84061, 2.33673 48.83965, ..."
4,750001537,750000020,20,20ème Ardt,10704.483774,5.983446e+06,10704.940486,Ménilmontant,75120,20,"POLYGON ((2.41277 48.87547, 2.41284 48.87524, ..."
5,750001537,750000007,7,7ème Ardt,8099.033151,4.090057e+06,8099.424883,Palais-Bourbon,75107,7,"POLYGON ((2.32090 48.86306, 2.32094 48.86305, ..."
6,750001537,750000011,11,11ème Ardt,8281.635288,3.665442e+06,8282.011886,Popincourt,75111,11,"POLYGON ((2.39624 48.85415, 2.39708 48.85308, ..."
7,750001537,750000013,13,13ème Ardt,11545.686986,7.149311e+06,11546.546526,Gobelins,75113,13,"POLYGON ((2.37491 48.83801, 2.37698 48.83610, ..."
8,750001537,750000004,4,4ème Ardt,5420.636779,1.600586e+06,5420.908434,Hôtel-de-Ville,75104,4,"POLYGON ((2.36851 48.85573, 2.36900 48.85374, ..."
9,750001537,750000008,8,8ème Ardt,7880.260661,3.880036e+06,7880.533268,Élysée,75108,8,"POLYGON ((2.32584 48.86956, 2.32569 48.86954, ..."
10,750001537,750000018,18,18ème Ardt,9916.303827,5.996051e+06,9916.464176,Buttes-Montmartre,75118,18,"POLYGON ((2.36580 48.88554, 2.36469 48.88437, ..."
11,750001537,750000009,9,9ème Ardt,6471.389144,2.178303e+06,6471.588290,Opéra,75109,9,"POLYGON ((2.33978 48.88203, 2.33982 48.88202, ..."
12,750001537,750000019,19,19ème Ardt,11252.943229,6.792651e+06,11253.182479,Buttes-Chaumont,75119,19,"POLYGON ((2.38943 48.90122, 2.39014 48.90108, ..."
13,750001537,750000015,15,15ème Ardt,13677.923661,8.494994e+06,13678.798315,Vaugirard,75115,15,"POLYGON ((2.29932 48.85217, 2.30088 48.85118, ..."
14,750001537,750000003,3,3ème Ardt,4519.071982,1.170883e+06,4519.263648,Temple,75103,3,"POLYGON ((2.36383 48.86750, 2.36389 48.86747, ..."
15,750001537,750000005,5,5ème Ardt,6238.823408,2.539375e+06,6239.195396,Panthéon,75105,5,"POLYGON ((2.36443 48.84614, 2.36484 48.84584, ..."
16,750001537,750000006,6,6ème Ardt,6483.324560,2.153096e+06,6483.686786,Luxembourg,75106,6,"POLYGON ((2.34459 48.85405, 2.34428 48.85375, ..."
17,750001537,750000012,12,12ème Ardt,24088.038922,1.631478e+07,24089.666298,Reuilly,75112,12,"POLYGON ((2.41388 48.83357, 2.41401 48.83357, ..."
18,750001537,750000010,10,10ème Ardt,6739.168359,2.891739e+06,6739.375055,Entrepôt,75110,10,"POLYGON ((2.36469 48.88437, 2.36485 48.88436, ..."
19,750001537,750000016,16,16ème Ardt,17415.326726,1.637254e+07,17416.109657,Passy,75116,16,"POLYGON ((2.27427 48.87837, 2.27749 48.87796, ..."

In [25]:
import sys
sys.setrecursionlimit(150000)

paris_geo =  geo_data.merge(parcoord_df, right_on = 'Number', left_on = 'objectid')

paris_geo

,n_sq_co,n_sq_ar,objectid,l_ar,longueur,surface,perimetre,l_aroff,c_arinsee,c_ar,geometry,Arrond,Name,Address,Latitude,Longitude
0,750001537,750000001,1,1er Ardt,6054.680862,1.824613e+06,6054.936862,Louvre,75101,1,"POLYGON ((2.32801 48.86992, 2.32997 48.86851, ...",1st (Ier) R,Louvre,"[1er - Louvre, Palais Royale]",48.861970,2.339370
1,750001537,750000002,2,2ème Ardt,4553.938764,9.911537e+05,4554.104360,Bourse,75102,2,"POLYGON ((2.35152 48.86443, 2.35095 48.86341, ...",2nd (IIe) R,Bourse,[2ème - Bourse],48.868560,2.341614
2,750001537,750000017,17,17ème Ardt,10775.348915,5.668835e+06,10775.579516,Batignolles-Monceau,75117,17,"POLYGON ((2.29517 48.87396, 2.29504 48.87378, ...",17th (XVIIe) R,Batignolles-Monceau,[17ème - Palais de Congrès],48.878320,2.283730
3,750001537,750000014,14,14ème Ardt,10316.720258,5.614877e+06,10317.483310,Observatoire,75114,14,"POLYGON ((2.33381 48.84061, 2.33673 48.83965, ...",14th (XIVe) L,Observatoire,[14ème - Montparnasse],48.844873,2.327844
4,750001537,750000020,20,20ème Ardt,10704.483774,5.983446e+06,10704.940486,Ménilmontant,75120,20,"POLYGON ((2.41277 48.87547, 2.41284 48.87524, ...",20th (XXe) R,Ménilmontant,"[20ème - Belleville, Père Lachaise]",48.863727,2.397408
5,750001537,750000007,7,7ème Ardt,8099.033151,4.090057e+06,8099.424883,Palais-Bourbon,75107,7,"POLYGON ((2.32090 48.86306, 2.32094 48.86305, ...",7th (VIIe) L,Palais-Bourbon,[7ème - Eiffel Tower],48.858600,2.293980
6,750001537,750000011,11,11ème Ardt,8281.635288,3.665442e+06,8282.011886,Popincourt,75111,11,"POLYGON ((2.39624 48.85415, 2.39708 48.85308, ...",11th (XIe) R,Popincourt,[11ème - Bastille],48.847690,2.367466
7,750001537,750000013,13,13ème Ardt,11545.686986,7.149311e+06,11546.546526,Gobelins,75113,13,"POLYGON ((2.37491 48.83801, 2.37698 48.83610, ...",13th (XIIIe) L,Gobelins,[13ème - Place d'Italie],48.832083,2.356319
8,750001537,750000004,4,4ème Ardt,5420.636779,1.600586e+06,5420.908434,Hôtel-de-Ville,75104,4,"POLYGON ((2.36851 48.85573, 2.36900 48.85374, ...",4th (IVe) R,Hôtel-de-Ville,"[4ème - Marais, Hôtel de Ville]",48.857227,2.352404
9,750001537,750000008,8,8ème Ardt,7880.260661,3.880036e+06,7880.533268,Élysée,75108,8,"POLYGON ((2.32584 48.86956, 2.32569 48.86954, ...",8th (VIIIe) R,Élysée,[8ème - Champs-Elysées],48.869850,2.307210
10,750001537,750000018,18,18ème Ardt,9916.303827,5.996051e+06,9916.464176,Buttes-Montmartre,75118,18,"POLYGON ((2.36580 48.88554, 2.36469 48.88437, ...",18th (XVIIIe) R,Butte-Montmartre,[18ème - Montmartre],48.871921,2.340723
11,750001537,750000009,9,9ème Ardt,6471.389144,2.178303e+06,6471.588290,Opéra,75109,9,"POLYGON ((2.33978 48.88203, 2.33982 48.88202, ...",9th (IXe) R,Opéra,"[9ème - Opéra, Pigalle]",48.882013,2.337608
12,750001537,750000019,19,19ème Ardt,11252.943229,6.792651e+06,11253.182479,Buttes-Chaumont,75119,19,"POLYGON ((2.38943 48.90122, 2.39014 48.90108, ...",19th (XIXe) R,Buttes-Chaumont,[19ème - Parc de la Villette],48.873149,2.375512
13,750001537,750000015,15,15ème Ardt,13677.923661,8.494994e+06,13678.798315,Vaugirard,75115,15,"POLYGON ((2.29932 48.85217, 2.30088 48.85118, ...",15th (XVe) L,Vaugirard,[15ème - Parc des Expositions],48.834100,2.290010
14,750001537,750000003,3,3ème Ardt,4519.071982,1.170883e+06,4519.263648,Temple,75103,3,"POLYGON ((2.36383 48.86750, 2.36389 48.86747, ...",3rd (IIIe) R,Temple,"[3ème - Marais, Picasso Museum]",48.857170,2.341400
15,750001537,750000005,5,5ème Ardt,6238.823408,2.539375e+06,6239.195396,Panthéon,75105,5,"POLYGON ((2.36443 48.84614, 2.36484 48.84584, ...",5th (Ve) L,Panthéon,[5ème - Latin Quarter],48.847750,2.351800
16,750001537,750000006,6,6ème Ardt,6483.324560,2.153096e+06,6483.686786,Luxembourg,75106,6,"POLYGON ((2.34459 48.85405, 2.34428 48.85375, ...",6th (VIe) L,Luxembourg,[6ème - Saint Germain],48.849450,2.355081
17,750001537,750000012,12,12ème Ardt,24088.038922,1.631478e+07,24089.666298,Reuilly,75112,12,"POLYGON ((2.41388 48.83357, 2.41401 48.83357, ...",12th (XIIe) R,Reuilly,[12ème - Bercy],48.845029,2.406192
18,750001537,750000010,10,10ème Ardt,6739.168359,2.891739e+06,6739.375055,Entrepôt,75110,10,"POLYGON ((2.36469 48.88437, 2.36485 48.88436, ...",10th (Xe) R,Entrepôt,[10ème - Canal St. Martin],48.847190,2.366580
19,750001537,750000016,16,16ème Ardt,17415.326726,1.637254e+07,17416.109657,Passy,75116,16,"POLYGON ((2.27427 48.87837, 2.27749 48.87796, ...",16th (XVIe) R,Passy,[16ème - Trocadéro],48.862534,2.282255

In [0]:
#!git clone https://github.com/geopandas/geopandas.git
#!cd geopandas
#!pip install .
#!pip install geopandas

In [0]:
import geopandas
import matplotlib.pyplot as plt
import shapely 

paris_arr = geopandas.GeoDataFrame(paris_geo)
paris_arr.to_csv('paris_arr.csv')

#geoplot.polyplot(paris_arr, figsize=(8, 4))

#arr_locations = geopandas.tools.geocode(paris_arr.l_aroff)

#paris_arr.l_aroff

#paris_arr_locations

#fig, ax = plt.subplots()

#paris_arr.to_crs("EPSG:4326").plot(ax=ax, color="white", edgecolor="black")

#paris_arr_locations.plot(ax=ax, color="red")

arrondissements_p = geopandas.read_file('paris_arr.csv')
arrondissements_p.set_index('c-ar', inplace=True)
arrondissements_p.sort_index(inplace=True)
arrondissements_p

In [0]:
3def my_color_function(feature):
    """Maps low values to green and hugh values to red."""
    if pop_dict[feature['id']] > 6.5:
        return '#ff0000'
    else:
        return '#008000'

In [0]:
json.load('/content/drive/My Drive/Colab Notebooks/arrondissements.geojson

In [0]:
paris_map = folium.Map(location=[latitude, longitude], zoom_start=13)

colordict = {0: 'lightblue', 1: 'lightgreen', 2: 'orange', 3: 'red', 4: 'beige'}

folium.Choropleth(
    geo_data = '/content/drive/My Drive/Colab Notebooks/arrondissements.geojson',
    data = parcoord_df,
    columns = ['Latitude', 'Longitude', 'Address', 'Name'],
    key_on = parcoord_df['Number'],
    bins = 20,
    fill_color = my_color_function(['#66c2a5','#fc8d62','#8da0cb', '#ffffff']),
    fill_opacity =  0.6,
    line_opacity = 1,
    name = None, 
    legend_name = '',
    overlay = True, 
    control = True, 
    topojson = None, 
    smooth_factor = None).add_to(paris_map)
    
paris_map

  #[latitude, longitude],
        #radius=15,
        #popup = ('Arrondissement: ' + str(address).capitalize() + '<br>'),
        #color ='colordict',
        #key_on = 'Arr#',
        #threshold_scale=[0,1,2,3,4,5],  #[latitude, longitude],
        #radius=15,
        #popup = ('Arrondissement: ' + str(address).capitalize() + '<br>'),
        #color ='colordict',
        #key_on = 'Arr#',
        #threshold_scale=[0,1,2,3,4,5],

#### Find the center cooordinates of Atlanta GA, and create a map with folium contaning coordinates from DataFrame

In [0]:
Atl_map.save('Atl_map.html')

#### Enter Credentials from FourSquare

In [0]:
CLIENT_ID = 'U4KD030Y4D1W4KHOW2TIKATHHUT4Z1NS2XR1T5FHYHTMCMPZ'
CLIENT_SECRET = 'AZUKDNM2EGIRD1PPR5DVQY114QXGWTAJUTN00Q5ABI0TBFF0' 
VERSION = '20180604'

LIMIT = 30

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)

folium.vector_layers.CircleMarker(
    [lat,lng],
    radius=5,
    color='red',
    popup=label,
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(paris_map)

#### Pull Venue Data from FourSquare for neighborhood coordinates

In [0]:
radius = 1000
LIMIT = 100

venues = []

for lat, long, neighborhood in zip(Atl_df['Latitude'], Atl_df['Longitude'], Atl_df['Neighborhood']): 
    url = 'https://api.foursquare.com/v2/venues/explore?client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
        CLIENT_ID,
        CLIENT_SECRET,
        VERSION,
        lat,
        long,
        radius, 
        LIMIT)
    
    results = requests.get(url).json()['response']['groups'][0]['items']
    
    for venue in results:
        venues.append((
            neighborhood,
            lat, 
            long, 
            venue['venue']['name'], 
            venue['venue']['location']['lat'], 
            venue['venue']['location']['lng'],  
            venue['venue']['categories'][0]['name']))

In [0]:
venues_df = pd.DataFrame(venues)

venues_df.columns = ['Neighborhood', 'Latitude', 'Longitude', 'VenueName', 'VenueLatitude', 'VenueLongitude', 'VenueCategory']
df_na = venues_df['Neighborhood'] != 'Na'
venues_df = venues_df[df_na]
print(venues_df.shape)
venues_df.head()

In [0]:
venues_df.tail()

In [0]:
venues_df.groupby(['Neighborhood']).count()

In [0]:
print('There are {} unique categories.'.format(len(venues_df['VenueCategory'].unique())))

In [0]:
venues_df['VenueCategory'].unique()[:]

In [0]:
'Furniture / Home Store' in venues_df['VenueCategory'].unique()

In [0]:
atl_hot = pd.get_dummies(venues_df[['VenueCategory']], prefix="", prefix_sep="")

atl_hot['Neighborhoods'] = venues_df['Neighborhood'] 

fixed_columns = [atl_hot.columns[-1]] + list(atl_hot.columns[:-1])
atl_hot = atl_hot[fixed_columns]

print(atl_hot.shape)
atl_hot.head()

In [0]:
atl_hot.tail()

In [0]:
atl_hot_grouped = atl_hot.groupby(['Neighborhoods']).mean().reset_index()

print(atl_hot_grouped.shape)
atl_hot_grouped

#### Determine the number of Furniture Stores, isolate the stores and compare to areas with anituques, prepare data for clustering

In [0]:
len(atl_hot_grouped[atl_hot_grouped['Furniture / Home Store'] > 0])

In [0]:
atl_furniture = atl_hot_grouped[['Neighborhoods','Furniture / Home Store','Antique Shop']]

In [0]:
atl_furniture_group = atl_furniture.groupby(['Neighborhoods']).mean().reset_index()
atl_furniture_group

#### Cluster Furnture Store Data

In [0]:
kclusters = 9

atl_clustering = atl_furniture_group.drop(['Neighborhoods'], 1)

kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(atl_clustering)

kmeans.labels_[1:121]

In [0]:
atl_merged = atl_furniture_group.copy()

atl_merged['Cluster Labels'] = kmeans.labels_

#### Add Cluster Labels to Data

In [0]:
atl_merged.groupby(['Cluster Labels'], as_index=False)['Furniture / Home Store'].mean()
atl_merged

#### Clusters that have Antique Shops

In [0]:
f_atl = atl_merged['Antique Shop'] != 0
atl_merged[f_atl]

In [0]:
atl_merged.rename(columns={'Neighborhoods': 'Neighborhood'}, inplace=True)
atl_merged.head()

In [0]:
atl_merged = atl_merged.join(venues_df.set_index('Neighborhood'), on='Neighborhood')

atl_merged.shape
atl_merged.head()

In [0]:
print(atl_merged.shape)
atl_merged.sort_values(['Cluster Labels'], inplace=True)

#### Plot Map of Clusters, color coded

In [0]:
atl_map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

markers_colors = []
for lat, lon, poi, cluster in zip(atl_merged['Latitude'], atl_merged['Longitude'], atl_merged['Neighborhood'], atl_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' - Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(atl_map_clusters)
       
atl_map_clusters

In [0]:
atl_map_clusters.save('atl_map.html')

In [0]:
atl_merged.groupby(['Cluster Labels'], as_index=False)['Furniture / Home Store'].mean()

In [0]:
top_neigh = atl_hot_grouped[atl_hot_grouped['Furniture / Home Store'] != 0 ]

#### Rank Furniture Stores in city = 20 most frequent

In [0]:
num_top_venues = 25

#for neigh in top_neigh['Neighborhoods']:
    #print("----"+neigh+"----")
temp = top_neigh[top_neigh['Neighborhoods'] == neigh].T.reset_index()
temp.columns = ['venue','freq']
temp = temp.iloc[1:]
temp['freq'] = temp['freq'].astype(float)
temp = temp.round({'freq': 2})
print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
print('\n')

#### Neighborhoods with No Furniture Home Stores and No Antique Stores

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 0].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

#### All Furniture Stores in Atlanta

In [0]:
df2 = atl_merged['VenueCategory'] == 'Furniture / Home Store'
atl_all_furn = atl_merged[df2].sort_values(['Cluster Labels'])
atl_all_furn

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 1].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

#### Only one store in North Buckhead

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 3].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

#### Cluster 4 has 11 neighborhoods with Furniture Stores

In [0]:
v4 = atl_merged.loc[atl_merged['Cluster Labels'] == 4].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()
v4

In [0]:
v4['Furniture / Home Store'].sum()

In [0]:
v5 = atl_merged.loc[atl_merged['Cluster Labels'] == 5].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()
v5

In [0]:
v5['Furniture / Home Store'].sum()

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 6].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 7].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

#### Cluster 7 has 3 neighboorhoods with 10 stores, the detail of each location is below

In [0]:
v7 = atl_all_furn['Cluster Labels'] == 7
atl_all_furn[v7]

#### Cluster 8 has high numbers too

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 8].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

In [0]:
v8 = atl_all_furn['Cluster Labels'] == 8
atl_all_furn[v8]

In [0]:
atl_merged.loc[atl_merged['Cluster Labels'] == 9].groupby(['Neighborhood'], as_index=False)['Furniture / Home Store'].sum()

#### 9 has none